//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultari
    {
        public int ID { get; set; }
        public int ID_Medic { get; set; }
        public int ID_Pacient { get; set; }
        public System.DateTime Data { get; set; }
        public double Cost { get; set; }
        public string Boala { get; set; }
        public string Cauze { get; set; }
        public string Simptome { get; set; }
        public string Analize_recomandate { get; set; }
        public string Prescriptie_medicala { get; set; }
    }
}
