//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proiect1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacient()
        {
            this.Medic_Pacient = new HashSet<Medic_Pacient>();
        }
    
        public int ID { get; set; }
        public string CNP { get; set; }
        public int NrBuletin { get; set; }
        public string SerieBuletin { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Mail { get; set; }
        public string Parola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medic_Pacient> Medic_Pacient { get; set; }
    }
}
